### ISSUE TITLE
GPS antenna

### ISSUE THREAD

**Issue by BenRoe** [dekuNukem/exixe_clock#1]
I have built the exixe modules and the clock pcb.
Now i am searching which kind of gps antenna i have to use.
Is a active antenna a must? Which one do you use?

**Comment by dekuNukem** [comment]
It uses the very popular "black puck" antenna with the SMA connector like this one:

https://www.sparkfun.com/products/14986

Those antennas are very cheap on ebay or amazon.

**Comment by BenRoe** [comment]
Thanks for the quick answer.
This kind of antenna are very big and not looking very nice. 🙁
Is there a reason why you not used a surface mount smd antenna like this?
https://www.digikey.com/en/product-highlight/y/yageo/gps-glonass-antennas

**Comment by dekuNukem** [comment]
GPS antenna needs some open air to pick up the signal, and not everyone will have the clock right by a window if I soldered the antenna on the circuit board itself. So I feel that using an connector for external antenna is more suitable solution, and it's also cheaper.
