### ISSUE TITLE
Request for submitting Gerber files

### ISSUE THREAD

**Issue by jaromczyk** [dekuNukem/exixe_clock#5]
Hi,
thanks for sharing this project, it is really awesome!

I was trying to import the project onto KiCad to generate the Gerber files, but I get some errors - it would be best if one was simply to download the gerber files and then getting them manufactured.

Thanks again!

**Comment by dekuNukem** [comment]
I've added the gerber file in the repo, you can find it here:

https://github.com/dekuNukem/exixe_clock/blob/master/pcb/clock_v2_gerber.zip

**Comment by jaromczyk** [comment]
Thank you very much! Could you do the same for the exixe modules?
Thanks again!

**Comment by dekuNukem** [comment]
https://github.com/dekuNukem/exixe/blob/master/pcb/exixe12/exixe12_gerber.zip

https://github.com/dekuNukem/exixe/blob/master/pcb/exixe14/exixe14_gerber.zip

**Comment by jaromczyk** [comment]
Thanks!
Closing this issue.
